permalink: /:title/
url: hmbd.github.io
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20 # 每页显示篇数
paginate_path: "page:num"
name: 踏雪寻梅
description: 踏雪寻梅 | Stop talking, start doing.
author: HJD
email: 1131909224m@gmail.com
duoshuo: hmbd # 多说评论功能
weibo: 3720825601 # 微博用户主页显示的
hub: hmbd # github名字
safe: false
about: "弱菜一枚"

# ======================== makrdown配置 ========================
# ======================== 1 ========================
#markdown: redcarpet
#pygments: true

# ======================== 2 ========================
#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#    syntax_highlighter: rouge
#    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

# ======================== 3 ========================
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
